store_name = input("Store name: ")
customer_name = input("Customer name: ")
product_name = input("Product name: ")
product_price = float(input("Product price: "))
quantity = int(input("Quantity: "))
subtotal = int((product_price * quantity))
tax = float((subtotal * 0.115))
total = float((subtotal + tax))


print("\nReceipt")
print("-------")
print(f"Store: {store_name}")
print(f"Customer: {customer_name}")
print(f"Product: {product_name}")
print(f"Price: ${product_price}")
print(f"Quantity: {quantity}")
print(f"Subtotal ${subtotal}")
print(f"Tax: ${tax}")
print(f"Total: ${total}")

